package com.Training;

public class Jpr1 {

	public static void main(String[] args) {
		System.out.println("Sanika"+" sanika@gmail.com"+" P02150"+" 9951251153");
        System.out.println("Anika"+" anika@gmail.com"+" P02151"+" 9960231221");
        System.out.println("Avni"+" avni@gmail.com"+" P02152"+" 8665145420");
        System.out.println("Ganesh"+" ganesh@gmail.com"+" P02153"+" 7757095343");
        System.out.println("Aditya"+" Aditya@gmail.com"+" P02154"+" 9840321455");


	}

}
